# docker-compose.yml - Updated for PostgreSQL

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15
    container_name: repaircoin-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: repaircoin
      POSTGRES_USER: repaircoin
      POSTGRES_PASSWORD: repaircoin123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/src/database/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "repaircoin", "-d", "repaircoin"]
      interval: 10s
      timeout: 5s
      retries: 5

  # RepairCoin Backend
  repaircoin-backend:
    build: .
    container_name: repaircoin-backend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      PORT: 3000
      
      # PostgreSQL Database
      DATABASE_URL: postgresql://repaircoin:repaircoin123@postgres:5432/repaircoin
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: repaircoin
      DB_USER: repaircoin
      DB_PASSWORD: repaircoin123
      
      # JWT
      JWT_SECRET: ${JWT_SECRET:-dev-secret-key-change-in-production}
      
      # Thirdweb (if you're using it)
      THIRDWEB_CLIENT_ID: ${THIRDWEB_CLIENT_ID}
      THIRDWEB_SECRET_KEY: ${THIRDWEB_SECRET_KEY}
      PRIVATE_KEY: ${PRIVATE_KEY}
      REPAIRCOIN_CONTRACT_ADDRESS: ${REPAIRCOIN_CONTRACT_ADDRESS:-0xd92ced7c3f4D8E42C05A4c558F37dA6DC731d5f5}
      
      # Admin
      ADMIN_ADDRESSES: ${ADMIN_ADDRESSES:-0x761E5E59485ec6feb263320f5d636042bD9EBc8c}
      
      # Optional
      FIXFLOW_WEBHOOK_SECRET: ${FIXFLOW_WEBHOOK_SECRET:-dev-webhook-secret}
      FRONTEND_URL: ${FRONTEND_URL:-http://localhost:3001}
    volumes:
      - ./logs:/app/logs
      - ./backend:/app/backend
    depends_on:
      postgres:
        condition: service_healthy
    command: npm run dev

volumes:
  postgres_data: