name: repaircoin-backend
region: nyc
services:
  - name: api
    environment_slug: node-js
    github:
      branch: main
      deploy_on_push: true
      repo: YOUR_GITHUB_USERNAME/repaircoin-backend
    build_command: npm run build
    run_command: npm start
    http_port: 3000
    instance_count: 1
    instance_size_slug: basic-xxs
    health_check:
      http_path: /api/health
      initial_delay_seconds: 30
      period_seconds: 10
      timeout_seconds: 3
      success_threshold: 1
      failure_threshold: 3
    envs:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "3000"
      - key: DB_HOST
        value: ${repaircoin-db.HOSTNAME}
      - key: DB_PORT
        value: ${repaircoin-db.PORT}
      - key: DB_NAME
        value: ${repaircoin-db.DATABASE}
      - key: DB_USER
        value: ${repaircoin-db.USERNAME}
      - key: DB_PASSWORD
        value: ${repaircoin-db.PASSWORD}
        type: SECRET
      - key: DB_CA_CERT
        value: ${repaircoin-db.CA_CERT}
        type: SECRET
      - key: JWT_SECRET
        type: SECRET
      - key: THIRDWEB_CLIENT_ID
        type: SECRET
      - key: THIRDWEB_SECRET_KEY
        type: SECRET
      - key: PRIVATE_KEY
        type: SECRET
      - key: REPAIRCOIN_CONTRACT_ADDRESS
        value: "0xd92ced7c3f4D8E42C05A4c558F37dA6DC731d5f5"
      - key: FRONTEND_URL
        value: "https://repaircoin.vercel.app"
      - key: ADMIN_ADDRESSES
        value: "0x761E5E59485ec6feb263320f5d636042bD9EBc8c"
      - key: ENABLE_SWAGGER
        value: "true"
databases:
  - name: repaircoin-db
    engine: PG
    production: false
    size: db-s-dev-database
    version: "15"